const parameters = "c_thumb,h_136,w_288/f_auto/q_auto/dpr_2.0";
const resObjList = {
  "07PP50N1": {
    id: "07PP50N1",
    primarySlug: "asia-quick-hamburg-lueneburgstr",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 927,
    popularity: 143,
    brand: {
      name: "Asia Quick",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/chains/de/asia_quick/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/generic/heroes/51/51_sushi_26`,
      heroImageUrlType: "STOCK",
      branchName: "Hamburg Lüneburger Straße",
    },
    cuisineTypes: ["sushi_51", "chinese_41", "thai_61"],
    rating: {
      votes: 1957,
      score: 4.5,
    },
    location: {
      streetAddress: "Lüneburger Straße 29",
      city: "Hamburg",
      country: "DE",
      lat: "53.4591664",
      lng: "9.9824821",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: false,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 30,
        durationRange: {
          min: 20,
          max: 45,
        },
        deliveryFeeDefault: 100,
        minOrderValue: 1090,
        lowestDeliveryFee: {
          from: 0,
          fee: 100,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 1871,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  "0N55NQ11": {
    id: "0N55NQ11",
    primarySlug: "koez-kapadokya-restaurant",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 1139,
    popularity: 166,
    brand: {
      name: "Köz Kapadokya Restaurant",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/restaurants/de/0N55NQ11/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/generic/heroes/291/generic`,
      heroImageUrlType: "STOCK",
      branchName: "",
    },
    cuisineTypes: ["doener_821", "turkish_31", "turkish-pizza_291"],
    rating: {
      votes: 1658,
      score: 4.6,
    },
    location: {
      streetAddress: "Veringstrasse 126",
      city: "Hamburg Wilhelmsburg",
      country: "DE",
      lat: "53.5065838",
      lng: "9.9864443",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: false,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 30,
        durationRange: {
          min: 20,
          max: 45,
        },
        deliveryFeeDefault: 300,
        minOrderValue: 4800,
        lowestDeliveryFee: {
          from: 0,
          fee: 300,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 4713,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  "0P3N1": {
    id: "0P3N1",
    primarySlug: "presto-pizzaservice-hamburg",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 1020,
    popularity: 54,
    brand: {
      name: "Presto Pizza",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/restaurants/de/0P3N1/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/generic/heroes/271/271_italian_pizza_145`,
      heroImageUrlType: "STOCK",
      branchName: "Neuwiedenthaler",
    },
    cuisineTypes: ["italian-pizza_271", "greek_91", "snacks_201"],
    rating: {
      votes: 3272,
      score: 4.1,
    },
    location: {
      streetAddress: "Neuwiedenthaler Straße 25",
      city: "Hamburg",
      country: "DE",
      lat: "53.4767",
      lng: "9.86991",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: false,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 30,
        durationRange: {
          min: 20,
          max: 45,
        },
        deliveryFeeDefault: 150,
        minOrderValue: 1500,
        lowestDeliveryFee: {
          from: 2500,
          fee: 0,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 5922,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "pinAtHome",
      "giropay",
      "bitpay",
    ],
  },
  "0PNQPR11": {
    id: "0PNQPR11",
    primarySlug: "pizza-max-hamburg-harburg",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: true,
    },
    priceRange: 1128,
    popularity: 196,
    brand: {
      name: "Pizza Max",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/chains/de/pizza_max/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/chains/de/pizza_max/headers/header`,
      heroImageUrlType: "CHAIN",
      branchName: "Hamburg-Harburg",
    },
    cuisineTypes: ["italian-pizza_271", "burgers_541", "pasta_1614", "2600"],
    rating: {
      votes: 1766,
      score: 4.2,
    },
    location: {
      streetAddress: "Mensingstraße 3",
      city: "Hamburg",
      country: "DE",
      lat: "53.4440453",
      lng: "9.9990008",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: false,
      discounts: true,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 30,
        durationRange: {
          min: 20,
          max: 45,
        },
        deliveryFeeDefault: 99,
        minOrderValue: 790,
        lowestDeliveryFee: {
          from: 0,
          fee: 99,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 3774,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  "0R7N00N1": {
    id: "0R7N00N1",
    primarySlug: "giros-king-1",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 1415,
    popularity: 88,
    brand: {
      name: "Giros King",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/restaurants/de/0R7N00N1/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/generic/heroes/1356/1356_gyros_1`,
      heroImageUrlType: "STOCK",
      branchName: "1",
    },
    cuisineTypes: ["greek_91", "gyros_1356", "2600"],
    rating: {
      votes: 1873,
      score: 4.5,
    },
    location: {
      streetAddress: "Bremer Straße 140",
      city: "Hamburg",
      country: "DE",
      lat: "53.4499959",
      lng: "9.9663075",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: true,
      discounts: true,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 40,
        durationRange: {
          min: 30,
          max: 55,
        },
        deliveryFeeDefault: 200,
        minOrderValue: 990,
        lowestDeliveryFee: {
          from: 0,
          fee: 200,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 2041,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "pinAtHome",
      "creditcardAtHome",
      "giropay",
      "bitpay",
    ],
  },
  "31N5557N": {
    id: "31N5557N",
    primarySlug: "viet-no-1",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 0,
    popularity: 112,
    brand: {
      name: "Viet No 1",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/restaurants/de/31N5557N/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/generic/heroes/261/261_vietnamese_14`,
      heroImageUrlType: "STOCK",
      branchName: "",
    },
    cuisineTypes: ["sushi_51", "curry_731", "vietnamese_261"],
    rating: {
      votes: 975,
      score: 4.7,
    },
    location: {
      streetAddress: "Wilhelmstraße 1",
      city: "Hamburg",
      country: "DE",
      lat: "53.4602017",
      lng: "9.9757548",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: true,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 25,
        durationRange: {
          min: 15,
          max: 40,
        },
        deliveryFeeDefault: 199,
        minOrderValue: 2000,
        lowestDeliveryFee: {
          from: 0,
          fee: 199,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 1434,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  "3537Q1": {
    id: "3537Q1",
    primarySlug: "uni-grill-house",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: true,
    },
    priceRange: 758,
    popularity: 39,
    brand: {
      name: "Uni Grill House",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/restaurants/de/3537Q1/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/generic/heroes/31/generic`,
      heroImageUrlType: "STOCK",
      branchName: "",
    },
    cuisineTypes: ["german_431", "turkish_31"],
    rating: {
      votes: 2099,
      score: 4.4,
    },
    location: {
      streetAddress: "Eissendorfer Straße 21",
      city: "Hamburg",
      country: "DE",
      lat: "53.460159",
      lng: "9.9753126",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: false,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 30,
        durationRange: {
          min: 20,
          max: 45,
        },
        deliveryFeeDefault: 200,
        minOrderValue: 1300,
        lowestDeliveryFee: {
          from: 0,
          fee: 200,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 1413,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  "3Q3N117N": {
    id: "3Q3N117N",
    primarySlug: "yoko-sushi-harburg",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: true,
    },
    priceRange: 0,
    popularity: 51,
    brand: {
      name: "Yoko Sushi",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/chains/de/yoko_sushi_new_2020/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/chains/de/yoko_sushi_new_2020/headers/header`,
      heroImageUrlType: "CHAIN",
      branchName: "Harburg",
    },
    cuisineTypes: ["sushi_51", "japanese_551", "poke-bowl_2318", "2600"],
    rating: {
      votes: 675,
      score: 4.5,
    },
    location: {
      streetAddress: "Bremer Straße 14",
      city: "Hamburg",
      country: "DE",
      lat: "53.4582428",
      lng: "9.9807911",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: false,
      discounts: true,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 25,
        durationRange: {
          min: 15,
          max: 40,
        },
        deliveryFeeDefault: 0,
        minOrderValue: 990,
        lowestDeliveryFee: {
          from: 0,
          fee: 0,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 1832,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  "3QN7377N": {
    id: "3QN7377N",
    primarySlug: "burger-im-gluck",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: true,
    },
    priceRange: 0,
    popularity: 75,
    brand: {
      name: "Burger mit Glücks",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/restaurants/de/3QN7377N/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/restaurants/de/3QN7377N/headers/header`,
      heroImageUrlType: "OWN",
      branchName: "",
    },
    cuisineTypes: ["burgers_541", "american_381", "falafel_1215", "2600"],
    rating: {
      votes: 1177,
      score: 4.3,
    },
    location: {
      streetAddress: "Neue Straße 19",
      city: "Hamburg",
      country: "DE",
      lat: "53.461613",
      lng: "9.978742",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: true,
      discounts: true,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 40,
        durationRange: {
          min: 30,
          max: 55,
        },
        deliveryFeeDefault: 99,
        minOrderValue: 899,
        lowestDeliveryFee: {
          from: 0,
          fee: 99,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 1523,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  N033N5R: {
    id: "N033N5R",
    primarySlug: "elbdoener",
    indicators: {
      isDeliveryByScoober: true,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 0,
    popularity: 4,
    brand: {
      name: "Elbdöner",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/restaurants/de/N033N5R/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/restaurants/de/N033N5R/headers/header`,
      heroImageUrlType: "OWN",
      branchName: "",
    },
    cuisineTypes: ["doener_821", "turkish_31"],
    rating: {
      votes: 15,
      score: 3.5,
    },
    location: {
      streetAddress: "Eißendorfer Straße 72",
      city: "Hamburg",
      country: "DE",
      lat: "53.4580305",
      lng: "9.9659488",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: true,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 40,
        durationRange: {
          min: 30,
          max: 50,
        },
        deliveryFeeDefault: 0,
        minOrderValue: 1000,
        lowestDeliveryFee: {
          from: 0,
          fee: 0,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: 1699831485,
          token:
            "1699831485,N033N5R,53.4676939,9.9581124,492697683,0-0:0;faba44aba35721bc09942f159c21b3659b6e51d467b5e1843213cbd94e8a5e0a",
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 1193,
        },
      },
    },
    paymentMethods: ["sofort", "paypal", "creditcard", "giropay", "bitpay"],
  },
  N07PQR7: {
    id: "N07PQR7",
    primarySlug: "schweinske-hamburg-neugraben",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 1051,
    popularity: 138,
    brand: {
      name: "Schweinske",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/chains/de/schweinske/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/chains/de/schweinske/headers/header`,
      heroImageUrlType: "CHAIN",
      branchName: "Hamburg Neugraben",
    },
    cuisineTypes: ["german_431", "schnitzel_1654", "breakfast_361"],
    rating: {
      votes: 2143,
      score: 4,
    },
    location: {
      streetAddress: "Cuxhavener Straße 342",
      city: "Hamburg",
      country: "DE",
      lat: "53.4725753",
      lng: "9.8531628",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: false,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 50,
        durationRange: {
          min: 40,
          max: 65,
        },
        deliveryFeeDefault: 149,
        minOrderValue: 1500,
        lowestDeliveryFee: {
          from: 0,
          fee: 149,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 6967,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  N0N5QR7: {
    id: "N0N5QR7",
    primarySlug: "schweinske-hamburg-eisendorfer",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 1084,
    popularity: 31,
    brand: {
      name: "Schweinske",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/chains/de/schweinske/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/chains/de/schweinske/headers/header`,
      heroImageUrlType: "CHAIN",
      branchName: "Hamburg Harburg Eißendorf",
    },
    cuisineTypes: ["burgers_541", "german_431", "schnitzel_1654"],
    rating: {
      votes: 740,
      score: 3.9,
    },
    location: {
      streetAddress: "Eißendorfer Straße 95",
      city: "Hamburg",
      country: "DE",
      lat: "53.4580661",
      lng: "9.9676866",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: false,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 30,
        durationRange: {
          min: 20,
          max: 45,
        },
        deliveryFeeDefault: 149,
        minOrderValue: 1500,
        lowestDeliveryFee: {
          from: 0,
          fee: 149,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 1244,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  N15O0QO: {
    id: "N15O0QO",
    primarySlug: "restaurant-zala-wandsbek",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 1182,
    popularity: 46,
    brand: {
      name: "Restaurant Zala Wandsbek",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/restaurants/de/N15O0QO/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/generic/heroes/71/71_indian_13`,
      heroImageUrlType: "STOCK",
      branchName: "",
    },
    cuisineTypes: ["indian_71", "asian_1864", "chicken_521"],
    rating: {
      votes: 2811,
      score: 4.2,
    },
    location: {
      streetAddress: "Wandsbeker Chaussee 279",
      city: "Hamburg Eilbek",
      country: "DE",
      lat: "53.5695894",
      lng: "10.05597",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: true,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 30,
        durationRange: {
          min: 20,
          max: 45,
        },
        deliveryFeeDefault: 100,
        minOrderValue: 8000,
        lowestDeliveryFee: {
          from: 0,
          fee: 100,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 13047,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  N35RRRQ: {
    id: "N35RRRQ",
    primarySlug: "cafe-bar-hamburg",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 1528,
    popularity: 57,
    brand: {
      name: "Cafe Bar Hamburg",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/restaurants/de/N35RRRQ/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/restaurants/de/N35RRRQ/headers/header`,
      heroImageUrlType: "PROFESSIONAL",
      branchName: "",
    },
    cuisineTypes: ["desserts_954", "lunch_351", "breakfast_361"],
    rating: {
      votes: 808,
      score: 4.8,
    },
    location: {
      streetAddress: "Eißendorfer Straße 103",
      city: "Hamburg",
      country: "DE",
      lat: "53.4579653",
      lng: "9.9668738",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: false,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 25,
        durationRange: {
          min: 15,
          max: 40,
        },
        deliveryFeeDefault: 100,
        minOrderValue: 900,
        lowestDeliveryFee: {
          from: 0,
          fee: 100,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 1227,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "pinAtHome",
      "giropay",
      "bitpay",
    ],
  },
  N3P0R3O: {
    id: "N3P0R3O",
    primarySlug: "alk-at-night-hamburg-1",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: true,
      isSponsored: false,
    },
    priceRange: 2152,
    popularity: 19,
    brand: {
      name: "ALK at NIGHT",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/restaurants/de/N3P0R3O/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/generic/heroes/201/201_snacks_1`,
      heroImageUrlType: "STOCK",
      branchName: "Hamburg",
    },
    cuisineTypes: ["snacks_201", "cake_251"],
    rating: {
      votes: 480,
      score: 2.8,
    },
    location: {
      streetAddress: "Rahlstedter Straße 10b",
      city: "Hamburg",
      country: "DE",
      lat: "53.5927512",
      lng: "10.1398042",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: false,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: true,
        isOpenForPreorder: true,
        openingTime: null,
        duration: 90,
        durationRange: {
          min: 80,
          max: 100,
        },
        deliveryFeeDefault: 1000,
        minOrderValue: 8000,
        lowestDeliveryFee: {
          from: 0,
          fee: 1000,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: true,
        isOpenForPreorder: true,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 18373,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  NO31ORO: {
    id: "NO31ORO",
    primarySlug: "burgerme-hamburg-buxtehuder-strasse",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 888,
    popularity: 153,
    brand: {
      name: "burgerme",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/chains/de/burgerme/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/chains/de/burgerme/headers/header`,
      heroImageUrlType: "CHAIN",
      branchName: "Hamburg Harburg",
    },
    cuisineTypes: ["burgers_541", "american_381", "snacks_201", "2600"],
    rating: {
      votes: 3075,
      score: 4.3,
    },
    location: {
      streetAddress: "Buxtehuder Straße 3",
      city: "Hamburg",
      country: "DE",
      lat: "53.4644853",
      lng: "9.9785638",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: true,
      discounts: true,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 30,
        durationRange: {
          min: 20,
          max: 45,
        },
        deliveryFeeDefault: 199,
        minOrderValue: 899,
        lowestDeliveryFee: {
          from: 0,
          fee: 199,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 1399,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  NO53757: {
    id: "NO53757",
    primarySlug: "mundfein-pizzawerkstatt-hh-hausbruch",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 1029,
    popularity: 84,
    brand: {
      name: "MUNDFEIN Pizzawerkstatt",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/chains/de/mundfein/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/chains/de/mundfein/headers/header`,
      heroImageUrlType: "CHAIN",
      branchName: "Hamburg-Hausbruch",
    },
    cuisineTypes: ["italian-pizza_271", "pasta_1614", "snacks_201"],
    rating: {
      votes: 2003,
      score: 4,
    },
    location: {
      streetAddress: "Cuxhavener Str. 152",
      city: "Hamburg",
      country: "DE",
      lat: "53.4722213",
      lng: "9.8874815",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: false,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 40,
        durationRange: {
          min: 30,
          max: 55,
        },
        deliveryFeeDefault: 150,
        minOrderValue: 1000,
        lowestDeliveryFee: {
          from: 0,
          fee: 150,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 4701,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  NOOO5RQ: {
    id: "NOOO5RQ",
    primarySlug: "urfa-kebab-neu-wulmstorf",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 945,
    popularity: 50,
    brand: {
      name: "Urfa Kebab",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/restaurants/de/NOOO5RQ/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/generic/heroes/271/271_italian_pizza_49`,
      heroImageUrlType: "STOCK",
      branchName: "Neu Wulmstorf",
    },
    cuisineTypes: ["italian-pizza_271", "doener_821", "turkish_31"],
    rating: {
      votes: 1276,
      score: 4.8,
    },
    location: {
      streetAddress: "Graf-Luckner-Weg 1",
      city: "Neu Wulmstorf",
      country: "DE",
      lat: "53.4594936",
      lng: "9.7805613",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: false,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 35,
        durationRange: {
          min: 25,
          max: 50,
        },
        deliveryFeeDefault: 200,
        minOrderValue: 3500,
        lowestDeliveryFee: {
          from: 0,
          fee: 200,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 11788,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  NP37N07: {
    id: "NP37N07",
    primarySlug: "food-night",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: true,
      isSponsored: false,
    },
    priceRange: 2166,
    popularity: 0,
    brand: {
      name: "Food Night",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/restaurants/de/NP37N07/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829684/static-takeaway-com/images/generic/heroes/954/954_desserts_13`,
      heroImageUrlType: "STOCK",
      branchName: "",
    },
    cuisineTypes: ["salads_1456", "desserts_954", "other_101", "2600"],
    rating: {
      votes: 229,
      score: 3.4,
    },
    location: {
      streetAddress: "Berner Heerweg 395",
      city: "Hamburg",
      country: "DE",
      lat: "53.6270077",
      lng: "10.1381711",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: true,
      discounts: true,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: true,
        isOpenForPreorder: true,
        openingTime: null,
        duration: 65,
        durationRange: {
          min: 55,
          max: 80,
        },
        deliveryFeeDefault: 1000,
        minOrderValue: 8000,
        lowestDeliveryFee: {
          from: 0,
          fee: 1000,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: true,
        isOpenForPreorder: true,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 21338,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  NQPR737: {
    id: "NQPR737",
    primarySlug: "mai-mai-hamburg-marktpassage",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: false,
    },
    priceRange: 0,
    popularity: 29,
    brand: {
      name: "Min 20",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/restaurants/de/NQPR737/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/generic/heroes/51/51_sushi_74`,
      heroImageUrlType: "STOCK",
      branchName: "",
    },
    cuisineTypes: ["sushi_51", "asian_1864", "vietnamese_261"],
    rating: {
      votes: 518,
      score: 4.1,
    },
    location: {
      streetAddress: "Marktpassage 5",
      city: "Hamburg",
      country: "DE",
      lat: "53.4702999",
      lng: "9.8516469",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: false,
      pickup: true,
      vouchers: true,
      stampCards: true,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 40,
        durationRange: {
          min: 30,
          max: 55,
        },
        deliveryFeeDefault: 200,
        minOrderValue: 1200,
        lowestDeliveryFee: {
          from: 0,
          fee: 200,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 7052,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  NR333RO: {
    id: "NR333RO",
    primarySlug: "hansekai-go",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: true,
    },
    priceRange: 2896,
    popularity: 38,
    brand: {
      name: "Hansekai GO!",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/restaurants/de/NR333RO/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/restaurants/de/NR333RO/headers/header`,
      heroImageUrlType: "PROFESSIONAL",
      branchName: "",
    },
    cuisineTypes: ["burgers_541", "american_381", "pasta_1614", "2600"],
    rating: {
      votes: 1493,
      score: 4.5,
    },
    location: {
      streetAddress: "Jaffestraße 12",
      city: "Hamburg",
      country: "DE",
      lat: "53.5084575",
      lng: "10.0006698",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: true,
      discounts: true,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 30,
        durationRange: {
          min: 20,
          max: 45,
        },
        deliveryFeeDefault: 0,
        minOrderValue: 2490,
        lowestDeliveryFee: {
          from: 0,
          fee: 0,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 5336,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
  NR5N00R: {
    id: "NR5N00R",
    primarySlug: "my-koez",
    indicators: {
      isDeliveryByScoober: false,
      isNew: false,
      isTestRestaurant: false,
      isGroceryStore: false,
      isSponsored: true,
    },
    priceRange: 1317,
    popularity: 116,
    brand: {
      name: "my KÖZ",
      logoUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/restaurants/de/NR5N00R/logo_465x320`,
      heroImageUrl: `https://res.cloudinary.com/tkwy-prod-eu/image/upload/${parameters}/v1699829685/static-takeaway-com/images/generic/heroes/31/31_turkish_40`,
      heroImageUrlType: "STOCK",
      branchName: "",
    },
    cuisineTypes: ["pasta_1614", "turkish_31", "lunch_351"],
    rating: {
      votes: 1969,
      score: 4.5,
    },
    location: {
      streetAddress: "Billhorner Röhrendamm 98",
      city: "Hamburg",
      country: "DE",
      lat: "53.5364742",
      lng: "10.0342371",
      timeZone: "Europe/Amsterdam",
    },
    supports: {
      delivery: true,
      pickup: true,
      vouchers: true,
      stampCards: true,
      discounts: false,
    },
    shippingInfo: {
      delivery: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        duration: 30,
        durationRange: {
          min: 20,
          max: 45,
        },
        deliveryFeeDefault: 350,
        minOrderValue: 4490,
        lowestDeliveryFee: {
          from: 0,
          fee: 350,
        },
        dynamicDeliveryFeeInfo: {
          expiryTime: null,
          token: null,
        },
      },
      pickup: {
        isOpenForOrder: false,
        isOpenForPreorder: false,
        openingTime: null,
        distance: {
          unit: "m",
          quantity: 9156,
        },
      },
    },
    paymentMethods: [
      "cash",
      "sofort",
      "paypal",
      "creditcard",
      "giropay",
      "bitpay",
    ],
  },
};

export default resObjList;
